# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CongregationWindow.ui',
# licensing of 'CongregationWindow.ui' applies.
#
# Created: Fri Apr 26 00:14:01 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_CongregationWindow(object):
    def setupUi(self, CongregationWindow):
        CongregationWindow.setObjectName("CongregationWindow")
        CongregationWindow.resize(323, 363)
        CongregationWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        CongregationWindow.setSizeGripEnabled(True)
        CongregationWindow.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(CongregationWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.list_congregation = QtWidgets.QListWidget(CongregationWindow)
        self.list_congregation.setObjectName("list_congregation")
        self.gridLayout.addWidget(self.list_congregation, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(CongregationWindow)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(6, 6, -1, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_delete = QtWidgets.QPushButton(self.frame_2)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.button_add = QtWidgets.QPushButton(self.frame_2)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.button_edit = QtWidgets.QPushButton(self.frame_2)
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout.addWidget(self.button_edit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(CongregationWindow)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_close = QtWidgets.QPushButton(self.frame)
        self.button_close.setObjectName("button_close")
        self.gridLayout_3.addWidget(self.button_close, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioAscending = QtWidgets.QRadioButton(self.frame_3)
        self.radioAscending.setToolTip("")
        self.radioAscending.setChecked(True)
        self.radioAscending.setObjectName("radioAscending")
        self.gridLayout_2.addWidget(self.radioAscending, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.radioDistance = QtWidgets.QRadioButton(self.frame_3)
        self.radioDistance.setEnabled(False)
        self.radioDistance.setObjectName("radioDistance")
        self.gridLayout_2.addWidget(self.radioDistance, 4, 0, 1, 1)
        self.radioDesending = QtWidgets.QRadioButton(self.frame_3)
        self.radioDesending.setToolTip("")
        self.radioDesending.setObjectName("radioDesending")
        self.gridLayout_2.addWidget(self.radioDesending, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)

        self.retranslateUi(CongregationWindow)
        QtCore.QObject.connect(self.button_close, QtCore.SIGNAL("clicked()"), CongregationWindow.close)
        QtCore.QMetaObject.connectSlotsByName(CongregationWindow)
        CongregationWindow.setTabOrder(self.button_add, self.button_edit)
        CongregationWindow.setTabOrder(self.button_edit, self.button_delete)
        CongregationWindow.setTabOrder(self.button_delete, self.radioAscending)
        CongregationWindow.setTabOrder(self.radioAscending, self.button_close)
        CongregationWindow.setTabOrder(self.button_close, self.list_congregation)

    def retranslateUi(self, CongregationWindow):
        CongregationWindow.setWindowTitle(QtWidgets.QApplication.translate("CongregationWindow", "Congregations", None, -1))
        self.button_delete.setText(QtWidgets.QApplication.translate("CongregationWindow", "Delete", None, -1))
        self.button_add.setText(QtWidgets.QApplication.translate("CongregationWindow", "Add", None, -1))
        self.button_edit.setText(QtWidgets.QApplication.translate("CongregationWindow", "Edit", None, -1))
        self.button_close.setText(QtWidgets.QApplication.translate("CongregationWindow", "Close", None, -1))
        self.radioAscending.setWhatsThis(QtWidgets.QApplication.translate("CongregationWindow", "Sort congregations by alphabetical order.", None, -1))
        self.radioAscending.setText(QtWidgets.QApplication.translate("CongregationWindow", "Ascending", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("CongregationWindow", "Sort by:", None, -1))
        self.radioDistance.setToolTip(QtWidgets.QApplication.translate("CongregationWindow", "Sort by distance has not been implemented yet.", None, -1))
        self.radioDistance.setText(QtWidgets.QApplication.translate("CongregationWindow", "Distance", None, -1))
        self.radioDesending.setWhatsThis(QtWidgets.QApplication.translate("CongregationWindow", "Sort congregations by reverse alphabetical order.", None, -1))
        self.radioDesending.setText(QtWidgets.QApplication.translate("CongregationWindow", "Desending", None, -1))

