# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui',
# licensing of 'MainWindow.ui' applies.
#
# Created: Sun Apr 14 22:43:58 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(479, 289)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.table_upcoming_talks = QtWidgets.QTableWidget(self.tab)
        self.table_upcoming_talks.setObjectName("table_upcoming_talks")
        self.table_upcoming_talks.setColumnCount(0)
        self.table_upcoming_talks.setRowCount(0)
        self.gridLayout.addWidget(self.table_upcoming_talks, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(43, 43))
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionDatabase = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MainWindow/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDatabase.setIcon(icon)
        self.actionDatabase.setObjectName("actionDatabase")
        self.actionBrothers = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/MainWindow/system-users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBrothers.setIcon(icon1)
        self.actionBrothers.setObjectName("actionBrothers")
        self.actionReports = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/MainWindow/x-office-presentation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReports.setIcon(icon2)
        self.actionReports.setObjectName("actionReports")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/MainWindow/preferences-system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon3)
        self.actionSettings.setObjectName("actionSettings")
        self.actionCongregation = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/MainWindow/go-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCongregation.setIcon(icon4)
        self.actionCongregation.setObjectName("actionCongregation")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/MainWindow/system-log-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon5)
        self.actionExit.setObjectName("actionExit")
        self.actionSchedule = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/MainWindow/schedule.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSchedule.setIcon(icon6)
        self.actionSchedule.setObjectName("actionSchedule")
        self.actionTalks = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/MainWindow/text-x-generic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTalks.setIcon(icon7)
        self.actionTalks.setObjectName("actionTalks")
        self.toolBar.addAction(self.actionDatabase)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBrothers)
        self.toolBar.addAction(self.actionCongregation)
        self.toolBar.addAction(self.actionTalks)
        self.toolBar.addAction(self.actionSchedule)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionReports)
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "pyTalkManager", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Upcoming talks", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Incoming speakers", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "Outgoing speakers", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.actionDatabase.setText(QtWidgets.QApplication.translate("MainWindow", "Database", None, -1))
        self.actionDatabase.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Tools relating to the database.", None, -1))
        self.actionBrothers.setText(QtWidgets.QApplication.translate("MainWindow", "Brothers", None, -1))
        self.actionBrothers.setToolTip(QtWidgets.QApplication.translate("MainWindow", "List of brothers to use.", None, -1))
        self.actionReports.setText(QtWidgets.QApplication.translate("MainWindow", "Reports", None, -1))
        self.actionReports.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Produce reports.", None, -1))
        self.actionSettings.setText(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.actionSettings.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Settings for pyTalkManager.", None, -1))
        self.actionCongregation.setText(QtWidgets.QApplication.translate("MainWindow", "Congregations", None, -1))
        self.actionCongregation.setToolTip(QtWidgets.QApplication.translate("MainWindow", "List of congregations", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionSchedule.setText(QtWidgets.QApplication.translate("MainWindow", "Schedule", None, -1))
        self.actionSchedule.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Set schedule", None, -1))
        self.actionTalks.setText(QtWidgets.QApplication.translate("MainWindow", "talks", None, -1))
        self.actionTalks.setToolTip(QtWidgets.QApplication.translate("MainWindow", "List of talk outlines", None, -1))

import gui.icons_rc
