# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OutlineWindow.ui',
# licensing of 'OutlineWindow.ui' applies.
#
# Created: Fri Apr 26 00:18:47 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_OutlineWindow(object):
    def setupUi(self, OutlineWindow):
        OutlineWindow.setObjectName("OutlineWindow")
        OutlineWindow.resize(495, 358)
        OutlineWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        OutlineWindow.setSizeGripEnabled(True)
        OutlineWindow.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(OutlineWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(OutlineWindow)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(6, 6, -1, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_delete = QtWidgets.QPushButton(self.frame_2)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.button_add = QtWidgets.QPushButton(self.frame_2)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.button_edit = QtWidgets.QPushButton(self.frame_2)
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout.addWidget(self.button_edit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(OutlineWindow)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.radio_title = QtWidgets.QRadioButton(self.frame_3)
        self.radio_title.setToolTip("")
        self.radio_title.setChecked(False)
        self.radio_title.setObjectName("radio_title")
        self.gridLayout_2.addWidget(self.radio_title, 2, 1, 1, 1)
        self.radio_number = QtWidgets.QRadioButton(self.frame_3)
        self.radio_number.setToolTip("")
        self.radio_number.setChecked(True)
        self.radio_number.setObjectName("radio_number")
        self.gridLayout_2.addWidget(self.radio_number, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 1, 0, 1, 1)
        self.button_import = QtWidgets.QPushButton(self.frame)
        self.button_import.setEnabled(True)
        self.button_import.setCheckable(False)
        self.button_import.setAutoDefault(True)
        self.button_import.setObjectName("button_import")
        self.gridLayout_3.addWidget(self.button_import, 1, 2, 1, 1)
        self.button_close = QtWidgets.QPushButton(self.frame)
        self.button_close.setObjectName("button_close")
        self.gridLayout_3.addWidget(self.button_close, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)
        self.table_outline = QtWidgets.QTableWidget(OutlineWindow)
        self.table_outline.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_outline.setProperty("showDropIndicator", False)
        self.table_outline.setAlternatingRowColors(False)
        self.table_outline.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_outline.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_outline.setShowGrid(False)
        self.table_outline.setWordWrap(True)
        self.table_outline.setCornerButtonEnabled(True)
        self.table_outline.setObjectName("table_outline")
        self.table_outline.setColumnCount(2)
        self.table_outline.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.table_outline.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outline.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outline.setHorizontalHeaderItem(1, item)
        self.table_outline.horizontalHeader().setVisible(True)
        self.table_outline.horizontalHeader().setCascadingSectionResizes(False)
        self.table_outline.horizontalHeader().setStretchLastSection(True)
        self.table_outline.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.table_outline, 0, 0, 1, 1)

        self.retranslateUi(OutlineWindow)
        QtCore.QObject.connect(self.button_close, QtCore.SIGNAL("clicked()"), OutlineWindow.close)
        QtCore.QMetaObject.connectSlotsByName(OutlineWindow)
        OutlineWindow.setTabOrder(self.button_add, self.button_edit)
        OutlineWindow.setTabOrder(self.button_edit, self.button_delete)
        OutlineWindow.setTabOrder(self.button_delete, self.radio_number)
        OutlineWindow.setTabOrder(self.radio_number, self.radio_title)
        OutlineWindow.setTabOrder(self.radio_title, self.button_close)
        OutlineWindow.setTabOrder(self.button_close, self.table_outline)

    def retranslateUi(self, OutlineWindow):
        OutlineWindow.setWindowTitle(QtWidgets.QApplication.translate("OutlineWindow", "Outline Manager", None, -1))
        self.button_delete.setToolTip(QtWidgets.QApplication.translate("OutlineWindow", "<html><head/><body><p>Delete the highlighted outline from the list.</p></body></html>", None, -1))
        self.button_delete.setText(QtWidgets.QApplication.translate("OutlineWindow", "Delete", None, -1))
        self.button_add.setToolTip(QtWidgets.QApplication.translate("OutlineWindow", "<html><head/><body><p>Adds a new outline to the list.</p></body></html>", None, -1))
        self.button_add.setText(QtWidgets.QApplication.translate("OutlineWindow", "Add", None, -1))
        self.button_edit.setToolTip(QtWidgets.QApplication.translate("OutlineWindow", "<html><head/><body><p>Edit the highlighted outline.</p></body></html>", None, -1))
        self.button_edit.setText(QtWidgets.QApplication.translate("OutlineWindow", "Edit", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("OutlineWindow", "Sort by outline:", None, -1))
        self.radio_title.setWhatsThis(QtWidgets.QApplication.translate("OutlineWindow", "Sort congregations by reverse alphabetical order.", None, -1))
        self.radio_title.setText(QtWidgets.QApplication.translate("OutlineWindow", "Title", None, -1))
        self.radio_number.setWhatsThis(QtWidgets.QApplication.translate("OutlineWindow", "Sort congregations by alphabetical order.", None, -1))
        self.radio_number.setText(QtWidgets.QApplication.translate("OutlineWindow", "Number", None, -1))
        self.button_import.setToolTip(QtWidgets.QApplication.translate("OutlineWindow", "<html><head/><body><p>Import a list of outlines to be used. The button becomes disabled after outlines have been imported.</p></body></html>", None, -1))
        self.button_import.setText(QtWidgets.QApplication.translate("OutlineWindow", "Import", None, -1))
        self.button_close.setText(QtWidgets.QApplication.translate("OutlineWindow", "Close", None, -1))
        self.table_outline.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("OutlineWindow", "New Row", None, -1))
        self.table_outline.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("OutlineWindow", "Number", None, -1))
        self.table_outline.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("OutlineWindow", "Title", None, -1))

