# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BrotherWindow.ui',
# licensing of 'BrotherWindow.ui' applies.
#
# Created: Fri Apr 26 00:00:04 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_BrotherWindow(object):
    def setupUi(self, BrotherWindow):
        BrotherWindow.setObjectName("BrotherWindow")
        BrotherWindow.resize(674, 382)
        BrotherWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        BrotherWindow.setAutoFillBackground(True)
        BrotherWindow.setSizeGripEnabled(True)
        BrotherWindow.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(BrotherWindow)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(BrotherWindow)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(BrotherWindow)
        self.frame_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.radio_coord = QtWidgets.QRadioButton(self.frame_6)
        self.radio_coord.setObjectName("radio_coord")
        self.gridLayout_6.addWidget(self.radio_coord, 5, 0, 1, 1)
        self.radio_ms = QtWidgets.QRadioButton(self.frame_6)
        self.radio_ms.setObjectName("radio_ms")
        self.gridLayout_6.addWidget(self.radio_ms, 3, 0, 1, 1)
        self.radio_all = QtWidgets.QRadioButton(self.frame_6)
        self.radio_all.setChecked(True)
        self.radio_all.setObjectName("radio_all")
        self.gridLayout_6.addWidget(self.radio_all, 1, 0, 1, 1)
        self.radio_elder = QtWidgets.QRadioButton(self.frame_6)
        self.radio_elder.setObjectName("radio_elder")
        self.gridLayout_6.addWidget(self.radio_elder, 1, 1, 1, 1)
        self.radio_pub = QtWidgets.QRadioButton(self.frame_6)
        self.radio_pub.setObjectName("radio_pub")
        self.gridLayout_6.addWidget(self.radio_pub, 3, 1, 1, 1)
        self.combo_cong = QtWidgets.QComboBox(self.frame_6)
        self.combo_cong.setObjectName("combo_cong")
        self.gridLayout_6.addWidget(self.combo_cong, 7, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_6, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.radio_fname = QtWidgets.QRadioButton(self.frame_4)
        self.radio_fname.setChecked(True)
        self.radio_fname.setObjectName("radio_fname")
        self.gridLayout_3.addWidget(self.radio_fname, 1, 0, 1, 1)
        self.radio_l_name = QtWidgets.QRadioButton(self.frame_4)
        self.radio_l_name.setObjectName("radio_l_name")
        self.gridLayout_3.addWidget(self.radio_l_name, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_4, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_3, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(BrotherWindow)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_close = QtWidgets.QPushButton(self.frame)
        self.button_close.setObjectName("button_close")
        self.gridLayout_2.addWidget(self.button_close, 0, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 4, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(BrotherWindow)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(6, 6, -1, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.button_delete = QtWidgets.QPushButton(self.frame_2)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.button_add = QtWidgets.QPushButton(self.frame_2)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.button_edit = QtWidgets.QPushButton(self.frame_2)
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout.addWidget(self.button_edit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)

        self.retranslateUi(BrotherWindow)
        QtCore.QObject.connect(self.button_close, QtCore.SIGNAL("clicked()"), BrotherWindow.close)
        QtCore.QMetaObject.connectSlotsByName(BrotherWindow)

    def retranslateUi(self, BrotherWindow):
        BrotherWindow.setWindowTitle(QtWidgets.QApplication.translate("BrotherWindow", "Brothers", None, -1))
        self.tableWidget.setWhatsThis(QtWidgets.QApplication.translate("BrotherWindow", "<html><head/><body><p>An orderd list of all the brothers entered into the database. Names are sorted first by <span style=\" font-style:italic;\">first</span> or <span style=\" font-style:italic;\">last</span> name and then by their congregation.</p></body></html>", None, -1))
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("BrotherWindow", "Name", None, -1))
        self.tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("BrotherWindow", "Congregation", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("BrotherWindow", "From:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("BrotherWindow", "Display:", None, -1))
        self.radio_coord.setText(QtWidgets.QApplication.translate("BrotherWindow", "Talk Coordinators", None, -1))
        self.radio_ms.setText(QtWidgets.QApplication.translate("BrotherWindow", "Ministial Servents", None, -1))
        self.radio_all.setText(QtWidgets.QApplication.translate("BrotherWindow", "All", None, -1))
        self.radio_elder.setText(QtWidgets.QApplication.translate("BrotherWindow", "Elders", None, -1))
        self.radio_pub.setText(QtWidgets.QApplication.translate("BrotherWindow", "Publishers", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("BrotherWindow", "Sort by:", None, -1))
        self.radio_fname.setWhatsThis(QtWidgets.QApplication.translate("BrotherWindow", "Sort the brother list by first names.", None, -1))
        self.radio_fname.setText(QtWidgets.QApplication.translate("BrotherWindow", "First name", None, -1))
        self.radio_l_name.setWhatsThis(QtWidgets.QApplication.translate("BrotherWindow", "Sort the brother list by last names.", None, -1))
        self.radio_l_name.setText(QtWidgets.QApplication.translate("BrotherWindow", "Last name", None, -1))
        self.button_close.setText(QtWidgets.QApplication.translate("BrotherWindow", "Close", None, -1))
        self.button_delete.setWhatsThis(QtWidgets.QApplication.translate("BrotherWindow", "Remove a brother from the list.", None, -1))
        self.button_delete.setText(QtWidgets.QApplication.translate("BrotherWindow", "Delete", None, -1))
        self.button_add.setWhatsThis(QtWidgets.QApplication.translate("BrotherWindow", "Add a brother to the list.", None, -1))
        self.button_add.setText(QtWidgets.QApplication.translate("BrotherWindow", "Add", None, -1))
        self.button_edit.setWhatsThis(QtWidgets.QApplication.translate("BrotherWindow", "Edit a brother\'s information.", None, -1))
        self.button_edit.setText(QtWidgets.QApplication.translate("BrotherWindow", "Edit", None, -1))

